server:
  port: 8888

spring:
  profiles:
    active:
    - native
  application:
    name: spring-cloud-config-server1
  cloud:
    config:
      server:
        git:
          uri: git@github.com:mimaraslan/spring-cloud-config-server1.git
          search-paths:
            - 'config*'
          #ignore-local-ssh-settings: true
          #strict-host-key-checking: false
          #search-paths:
          #- configuration/{application}/
          #- configuration/
          #private-key: |
          #              -----Your Private Key-----
                        
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/       
      
      