config:
  server:
    service-d1-key: Hello from Config Server - Services d1
processstart: 441
processstop: 442
rate: 443
price: 444    


spring:
  cloud:
    config:
      uri:
      - http://localhost:8888  